services:
  - type: web
    name: kahejo-app
    runtime: docker
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
